title: Hugin
default_lang: tr
author:
  name: 'Pazarlama Departmanı'
  email: huginfo@hugin.com.tr
taxonomies:
  - category
  - tag
metadata:
  description: 'Hugin Retail Solutions 85 yıldır ödeme sistemlerinde lider. Yeni nesil yazarkasa, ÖKC, perakende teknolojileri'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
email: huginfo@hugin.com.tr
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'
social:
  -
    url: 'https://www.facebook.com/huginretailsolutions/'
    icon: facebook
  -
    url: 'https://www.youtube.com/channel/UCmJ2I-IvgM5WVioEpReg_rg'
    icon: youtube
  -
    url: 'https://aboutme.google.com/b/110676450897212441441/'
    icon: google-plus
menu:
  -
    text: Features
    link: '#features'
  -
    text: Pricing
    link: '#pricing'
  -
    text: Screenshots
    link: '#screenshots'
  -
    text: Testimonials
    link: '#testimonials'
  -
    text: Subscribe
    link: '#subscribe'
footer:
  text: 'Her hakkı saklıdır. İzinsiz kopyalanamaz veya çoğaltılamaz. Copyright 2017 HUGIN A.Ş.'
  address:
    title: 'MERKEZ'
    lines:
      -
        line: 'Meclisi Mebusan'
      -
        line: 'Caddesi No.77/3'
      -
        line: 'Fındıklı, Istanbul'
      -
        line: '34427 TR'
  social_title: Sosyal medya
  contact:
    title: 'İLETİŞİM'
    lines:
      -
        text: 444.5.446
        url: '#'
      -
        text: 850.252.7272
        url: '#'
      -
        text: huginfo@hugin.com.tr
        url: 'mailto:huginfo@hugin.com.tr'
